### ISSUE TITLE
JSONC (JSON with Comments) Support

### ISSUE THREAD

**Issue by Sinjai** [josdejong/svelte-jsoneditor#222] opened 2023-02-07 04:46 UTC
Is there a possibility for support for JSON with Comments, like the `jsonc` "language" in VSCode? 

Or a recommendation for another library which can do this (even if otherwise less feature-rich)?

**Comment by josdejong** [comment] 2023-02-07 14:42
Duplicate of #157, let's continue the discussion there.

**Closed by josdejong** 2023-02-07 14:42 UTC

**Comment by Sinjai** [comment] 2023-02-19 23:22
Thanks, didn't know JSON5 is (includes?) JSONC.
