### ISSUE TITLE
svelte.preprocess depends on more than 10 external files

### ISSUE THREAD

**Issue by gerhardcit** [josdejong/svelte-jsoneditor#387] opened 2024-01-08 08:34 UTC
Building Sveltekit 2.0.6 app with vite 5.0.11
getting a lot of this.

```
node_modules/.pnpm/svelte-jsoneditor@0.21.1_@lezer+common@1.2.0/node_modules/svelte-jsoneditor/components/controls/navigationBar/NavigationBarDropdown.svelte svelte.preprocess depends on more than 10 external files which can cause slow builds and poor DX, try to reduce them. 
```

anything obvious that can cause this?

**Comment by josdejong** [comment] 2024-01-10 08:43
I have no idea what that is about. 

How can I reproduce your issue?

**Comment by madkarlsson** [comment] 2024-03-06 15:40
In my case, it comes from the fact that I use preprocess to prepend SCSS files (mixins/functions, etc.), and it doesn't like when it's too many of them. It's probably somewhere along that line.

**Comment by josdejong** [comment] 2024-03-06 15:44
Do you have a way to reproduce the issue for me Michael?

**Comment by madkarlsson** [comment] 2024-03-06 16:17
Not that I can share or put together quickly unfortunately but here is the gist:
In the below snippet, `scssPrependData` is a string that contains imports to more global SCSS imports (no actual CSS, only variables/mixins/functions and so on). When those imports become too many, it throws a warning for every component (since the import is also prepended for each component). It's hard to keep track off since the imports import things themselves as well

```js
// Svelte config
/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess({
			postcss: postcssConfig,
			scss: {
				prependData: scssPrependData,
			},
		}),
	],
```

**Comment by josdejong** [comment] 2024-03-13 09:19
Hm OK. So, what can cause this? I really have no clue, and without a way to reproduce I can't do any digging. Help would be welcome.

I had a look into the [`NavigationBarDropdown.svelte`](src/lib/components/controls/navigationBar/NavigationBarDropdown.svelte) file mentioned in the first error report in this issue, that imports a file `NavigationBarDropdown.scss`, which imports `styles.scss`, which imports `themes/defaults.scss` and that's it. The svelte-jsoneditor project does have more than 10 components though, I'm not sure if it is counting that?

**Comment by MattPurland** [comment] 2024-03-22 12:12
FYI: you can suppress the warning using the onwarn callback in the svelte processing in your vite config:

```
onwarn: (warning, handler) => {
                // e.g. don't warn on a11y-autofocus
                if (warning.code === 'a11y-click-events-have-key-events') return
                if (warning.code === 'vite-plugin-svelte-preprocess-many-dependencies') return;

                // let vite handle all other warnings normally
                handler(warning)
            },
```

**Comment by josdejong** [comment] 2024-03-27 11:13
Thanks for sharing your case Matt. 

> Importing over 10 sass files in a svelte component seems to cause this warning.

I indeed guess something like that is the case, I have no idea though which 10+ sass files this are in the case of `svelte-jsoneditor`: the [NavigationBarDropdown.svelte](https://github.com/josdejong/svelte-jsoneditor/issues/src/lib/components/controls/navigationBar/NavigationBarDropdown.svelte) component mentioned in [the first error report](https://github.com/josdejong/svelte-jsoneditor/issues/387#issue-2069964322) only imports [3 sass files](https://github.com/josdejong/svelte-jsoneditor/issues/387#issuecomment-1993895932).

The main question at this moment: how can I reproduce this issue? Anyone able to put together a minimal demo?

**Comment by josdejong** [comment] 2024-06-13 13:40
Closing this issue now, cannot do anything without a demo reproducing the issue. 

Please reopen if you have an example demonstrating the issue.

**Closed** 2024-06-13 13:40 UTC
Labels: help wanted
