### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by czalucky** [josdejong/svelte-jsoneditor#9] opened 2021-06-02 12:21 UTC
Using svelte-kit, this error seems to occur when onMount is present and the page is refreshed.

**Comment by josdejong** [comment] 2021-06-02 16:02
Thanks for reporting. How can I reproduce your issue exactly?

**Comment by plibither8** [comment] 2021-06-15 05:39
Same issue here, using Sapper. The problem arises because Sapper and SvelteKit run the `.svelte` file's code on the server too, which has the Node environment, and thus global variables like `navigator` are missing.

@czalucky Here's a workaround that worked for me:

```svelte
<script>
  import { onMount } from "svelte";

  let JSONEditor;

  onMount(async () => {
    ({ JSONEditor } = await import("svelte-jsoneditor"));
  });  
</script>

{#if JSONEditor}
  <svelte:component this={JSONEditor} bind:json />
{/if}
```

Since the import is now happening inside the `onMount`, this part of the code solely runs on the client's browser, and doesn't produce errors. Hope that helps :)

**Comment by josdejong** [comment] 2021-06-16 13:39
Thanks @plibither8 for sharing this workaround 👍 .

In commit https://github.com/josdejong/svelte-jsoneditor/commit/166c4666eb3f67ea4fa580020af656744da1733e I've created a possible fix for the missing `navigator` variable in a Sapper environment. How can I easily test whether this the editor works with Sapper? (I have no experience with Sapper yet).

**Comment by plibither8** [comment] 2021-06-16 19:47
Easiest way would be to create a Sapper app on your machine - very simple: https://sapper.svelte.dev/ - and edit the `src/routes/index.svelte` file. There you can import JSONEditor like in a normal Svelte app and use it. Try running it on the browser by doing `npm run dev` and opening `locahost:3000`.

**Comment by josdejong** [comment] 2021-06-23 09:42
Thanks for these pointers, exactly what I needed to quickly try this out.

The `navigator` error is now fixed indeed with the commit I mentioned. However, now the following error pops up:

```
TypeError: Cannot read property 'ace' of undefined
```

This is caused by the [ace editor](https://ace.c9.io/) also relying on the existence of `window`. That's out of my control unfortunately. We could open an issue at this project but don't think it's easy to resolve.

I guess we'll need to use the workaround you posted: https://github.com/josdejong/svelte-jsoneditor/issues/9#issuecomment-861186647

**Comment by josdejong** [comment] 2021-06-23 09:47
I couldn't find much about server side rendering of Ace, only this issue: https://github.com/ajaxorg/ace/issues/3990

**Comment by czalucky** [comment] 2021-06-23 12:02
When implementing your workaround we encountered the following:

![image](https://user-images.githubusercontent.com/13439212/123092801-e313ae00-d3f8-11eb-9c3d-0cbf009d3020.png)

We see this error when the component is unmounted (we are switching between tab components)

**Comment by josdejong** [comment] 2021-06-23 12:28
I think that is the same issue as #2

**Comment by josdejong** [comment] 2021-07-31 19:00
@plibither8 did you try out the async import workaround you shared in https://github.com/josdejong/svelte-jsoneditor/issues/9#issuecomment-861186647 in SvelteKit too? 

I'm trying to convert the library to SvelteKit and hitting some roadblocks related to the default SSR behavior ("window is not defined") and also your solution with dynamic import ("import not found: default").

**Comment by plibither8** [comment] 2021-07-31 19:29
Hey @josdejong! I haven't got the opportunity to try this on SvelteKit, I'll give it a go tomorrow and update on this thread :).

**Comment by josdejong** [comment] 2021-07-31 20:52
Thanks for your reply. I just found a solution a few minutes ago 🎉 , working that out soon. 

It's a bit of a workaround related to some issues in vite related to ssr and optimizeDeps (related to https://github.com/vitejs/vite/discussions/4230), but in the end you will not need to use the async import to be able to use jsoneditor, only need to add some (hopefully temporary) config for vite.

**Comment by plibither8** [comment] 2021-08-01 14:19
Great to know! Thanks :)

**Comment by josdejong** [comment] 2021-08-02 13:21
I've published `svelte-jsoneditor@0.2.1` which is refactored to a SvelteKit setup. 

The library is easier to setup now, though there is still an issue with Vite (used by SvelteKit) regarding dependencies. How to set it up is documented in the readme: https://github.com/josdejong/svelte-jsoneditor#sveltekit-setup

The new setup is more SSR friendly (as in: doesn't crash anymore). There is no need to import JSONEditor dynamically, this trick is done in JSONEditor itself for the part that cannot run SSR (the code editor).

Since this setup and sveltekit is very new I expect some rough edges, please let me know if you encounter any issues, and reopen this issue or create a new one.

**Closed by josdejong** 2021-08-02 13:21 UTC

**Comment by stringa** [comment] 2021-08-02 18:31
this does not fix dynamic imports for me.

**Comment by josdejong** [comment] 2021-08-03 07:40
@stringa you're talking about a nextjs setup, not SvelteKit, right?

If so, I would like to reserve this issue for SvelteKit SSR, and use #16 to discuss the issues with nextjs.
