### ISSUE TITLE
Opening a JSON gives a message stating the document is empty maybe 25% of the time.

### ISSUE THREAD

**Issue by joebells** [josdejong/svelte-jsoneditor#132] opened 2022-08-26 16:20 UTC
Hi,
First wanted to say thank you, this tool is amazing.
Lately when I try to load a JSON to look at or edit the tool sometimes gives a message stating the JSON is empty. I try the same JSON again and it loads. Not a huge deal, but wanted to mention it.
Thank you

**Comment by josdejong** [comment] 2022-08-26 19:59
Thanks Joe for your input. How can I reproduce your issue? How do you load JSON? Do you have an example document that regularly goes wrong or so?

**Comment by josdejong** [comment] 2022-08-31 14:46
Closing this issue now, can't do anything without more information.

**Closed by josdejong** 2022-08-31 14:46 UTC

**Comment by josdejong** [comment] 2022-09-12 09:20
I came across this issue myself today I think, when loading a large document from disk. It looks like it happens sometimes when you're on a slow machine and opening a large file. I've implemented a fix for this in `v6.6.5`. If this still happens, please let me know.
