### ISSUE TITLE
Extra newline inserted when pressing space on the start of a wrapped line in Chrome

### ISSUE THREAD

**Issue by neerajkanhere** [josdejong/svelte-jsoneditor#193] opened 2022-11-14 16:58 UTC
When a string value is long and has many spaces in the middle, the line-wrap behavior is correct on firefox, but on Chome the line gets split into a new line. The screenshot makes it clear.

**Comment by neerajkanhere** [comment] 2022-11-14 20:45
![line-split](https://user-images.githubusercontent.com/6738872/201762118-14c9d28a-9ac1-4014-ab1b-cd800ab9e47e.jpeg)

**Comment by josdejong** [comment] 2022-11-14 20:56
Thanks for reporting. Can you share the exact JSON document that you're using in your screenshots? I tried it out in Chrome and Firefox with a similar long string but it works fine in both browsers.

Is the issue still the case after refreshing the application in your browser with Ctrl+F5?

**Comment by neerajkanhere** [comment] 2022-11-28 16:42
![image](https://user-images.githubusercontent.com/6738872/204332976-8224b34f-67be-43a9-80ac-8e286edc123c.png)

**Comment by josdejong** [comment] 2022-11-29 12:22
Thanks for clarifying. I now tried to reproduce it with the following JSON:

```json
{
  "test": "a        b        c        d        e        f        g        h        i        j        k"
}
```

When I open this on both Firefox and Chrome and make sure the line wraps, they both behave like your Firefox screenshots: the value is rendered as three lines, not four, and the value is green.

What is your Chrome version? Do you have specific plugins or so installed in Chrome? Does it also happen when opening the editor in incognito mode?

**Comment by neerajkanhere** [comment] 2022-11-29 17:21
Using latest Chrome (version 107.0.5304.122 (Official Build) (64-bit)) on Windows 11 (with all updates). Tried it in private tab (with all extensions disabled). 
If you paste your sample document in Chrome, it shows green (with the correct wrap) as expected. But now if you click just before k (or the last letter) and start pressing the spacebar to introduce more spaces, eventually it turns gray (and introduces new line).  This only happens once you start entering spaces (not on pasting). In Firefox this doesn't happen, no matter how many spaces you introduce (using keyboard input, not just pasting) it keeps those as spaces and keeps it showing green.

**Comment by josdejong** [comment] 2022-12-01 09:11
Ahh, yes I can reproduce your issue, and indeed it only happens on Chrome.

So to reproduce: open the editor on Chrome, and open the following document:

```js
{
  "test": "a        b        c        d        e        f        g        h        i        j        k"
}
```
Make sure the line wraps. Then, put the caret on the first position of the wrapped line, like in the following screenshot:
![afbeelding](https://user-images.githubusercontent.com/568626/205012109-5fe972db-a575-4575-9270-837e64a27b13.png)

Then press `space` once. That will insert a new line and a space, instead of just a space.

I'll do some debugging to see if I can figure out why CodeMirror does that (and help would be welcome)

**Comment by josdejong** [comment] 2022-12-01 09:38
This turns out to be a Chrome bug: https://github.com/codemirror/dev/issues/968

The latest version of CodeMirror has a workaround fixing this in `@codemirror/view@6.6.0`.

**Comment by josdejong** [comment] 2022-12-01 10:04
Hmm, it looks like the fix was published in [`@codemirror/view@6.4.0`](https://github.com/codemirror/view/releases/tag/6.4.0), so this should have been fixed already (since `svelte-jsoneditor@0.9.1`, about one month ago).

To be continued...

**Comment by josdejong** [comment] 2022-12-20 09:39
I've verified the issue and reported it via https://github.com/codemirror/dev/issues/1038

**Comment by josdejong** [comment] 2022-12-20 13:38
Turns out CodeMirror has a working workaround for the Chrome issue. In my case, the issue was triggered again by the LastPass Chrome extension (see https://github.com/codemirror/dev/issues/1038#issuecomment-1359362497).

I'll close this issue now, not much we can do.

**Closed by josdejong** 2022-12-20 13:38 UTC
Labels: bug
