### ISSUE TITLE
Can we add a way to copy the PATH of a key?

### ISSUE THREAD

**Issue by iamumairayub** [josdejong/svelte-jsoneditor#152] opened 2022-09-29 11:06 UTC
Title of post says it all

I want to a way to copy the PATH of a key to clipboard so I dont have manually write it down into code

![image](https://user-images.githubusercontent.com/13570295/193015644-3ef63b1f-40cf-4c84-b742-3728f5200aff.png)

**Comment by josdejong** [comment] 2022-10-03 09:28
Yes, that can be very handy indeed. This is discussed already in #13, let's continue the discussion there. I'll close this issue as a duplicate of #13.

**Closed by josdejong** 2022-10-03 09:28 UTC
