### ISSUE TITLE
Sveltejs/kit 1.0.0-next.526 and above Incompatible with svelte-jsoneditor

### ISSUE THREAD

**Issue by ZaxyxaZ** [josdejong/svelte-jsoneditor#185] opened 2022-11-03 16:35 UTC
Updating to the latest version of "sveltejs/kit" above 1.0.0-next.525 version results in error while working with "svelte-jsoneditor" , The following error is displayed on the chrome developer console and app fails to start:

![image](https://user-images.githubusercontent.com/32272754/199778904-87a83183-efcc-4680-b7df-bc7b2e746bbe.png)

SyntaxError: The requested module '/node_modules/json-source-map/index.js?v=fda884be' does not provide an export named 'default' (at jsonUtils.js?v=fda884be:2:8)

Also surfaces in VSCode console as E:/dev/src/sveltekit/example-app/node_modules/ajv-dist/dist/ajv7.min.js" points to missing source files. As a result - the application never starts.

**Comment by josdejong** [comment] 2022-11-04 10:48
Thanks for reporting. 

I created a fresh new sveltekit project (with `@sveltejs/kit@1.0.0-next.532`), installed `svelte-jsoneditor`, add the 
`<JSONEditor ... />` component in `+page.svelte` (using VS Code), started a dev server, and opened it in Chrome. I do not see any of the warnings that you report so I guess I'm missing something?

How can I reproduce this issue?

**Comment by ZaxyxaZ** [comment] 2022-11-06 18:43
We did similar from scratch and added our application but have the same issue. What version of node are you using?We are using DaisyUI with Tailwinds. Those are the only other dependencies. We have tried similar approach with separate developers and get same problem.When we comment out the JSON-editor the app works fine. Best Regards,Andras R SzakalOn Nov 4, 2022, at 6:49 AM, Jos de Jong ***@***.***> wrote:﻿
Thanks for reporting.
I created a fresh new sveltekit project (with @***@***.***), installed svelte-jsoneditor, add the
<JSONEditor ... /> component in +page.svelte (using VS Code), started a dev server, and opened it in Chrome. I do not see any of the warnings that you report so I guess I'm missing something?
How can I reproduce this issue?

**Comment by josdejong** [comment] 2022-11-06 19:26
Is it possible to create a minimal demo of the problem? Like a [codesandbox](https://codesandbox.io/) example or so?

**Comment by ZaxyxaZ** [comment] 2022-11-06 19:39
Additional debug information from browser console:

client-manifest.js:18 SyntaxError: The requested module '/node_modules/json-source-map/index.js?v=e2e2c781' does not provide an export named 'default' (at jsonUtils.js?v=e2e2c781:2:8)

**Comment by seandlg** [comment] 2022-11-06 20:01
I'm seeing the same issue, but struggling to reproduce it. Will post an update once I manage to reproduce something..

**Comment by seandlg** [comment] 2022-11-06 21:12
It looks to me like a weird race condition. I can sometimes trigger the issue, by toggling `SSR` at the `+layout.js`-level, but I can't make it reproducible. I suspect it is related to `vitejs`.. In the course of debugging the issue, I did notice a wrong type import from `svelte-jsoneditor`, so I cannot rule out that this played a part..

**Comment by ZaxyxaZ** [comment] 2022-11-06 22:10
We thought about that…the app is driven by our back end APIs. One option could be to have a Webex were we walkthrough. Let us know if interested.It may take some time to create a stub example but will discuss with the dev team tomorrow.On Nov 6, 2022, at 2:26 PM, Jos de Jong ***@***.***> wrote:﻿
Is it possible to create a minimal demo of the problem? Like a codesandbox example or so?

**Comment by ZaxyxaZ** [comment] 2022-11-06 22:16
I’m only getting type and missing references. We are only using CSR in our app.Just to reiterate. This all started happening in v526 of SvelteKit. They did change some package references in that release. I tried to get Rich to look at it but he just closed the ticket suggesting it was not reproducible on his end. Best Regards,Andras R SzakalOn Nov 6, 2022, at 4:12 PM, Sean Eulenberg ***@***.***> wrote:﻿
It looks to me like a weird race condition. I can sometimes trigger the issue, by toggling SSR at the +layout.js-level, but I can't make it reproducible. I suspect it is related to vitejs.. In the course of debugging the issue, I did notice a wrong type import from svelte-jsoneditor, so I cannot rule out that this played a part..

**Comment by josdejong** [comment] 2022-11-07 08:26
> I can sometimes trigger the issue, by toggling `SSR` at the `+layout.js`-level

I did try that out, but still can't reproduce this at all 🤔 .

> In the course of debugging the issue, I did notice a wrong type import from `svelte-jsoneditor`

Is this an issue in the library? If so, what is the bug? That sounds like easily solvable

**Comment by gauravrawat440** [comment] 2022-11-07 14:38
> that
well @seandlg is right about the toggling the ssr at +layout.js , toggling it seems to have resolved the issue. The issue occurs from the dependency that is "json-source-map".  the error is as follows:

SyntaxError: The requested module '/node_modules/json-source-map/index.js?v=fda884be' does not provide an export named 'default

**Comment by ZaxyxaZ** [comment] 2022-11-07 15:29
So the issue can be overcome but it makes developing in SvelteKit almost impossible right now. We need to open a ticket in SvelteKit. I assume this is some sort of issue with Vite. And I'm not convinced that we know the root cause yet.

**Comment by ZaxyxaZ** [comment] 2022-11-07 22:47
@josdejong Looks like this is a Vite dev mode issue not resolving all dependencies. If any one else has issues just build and preview the app.

**Comment by bluwy** [comment] 2022-11-08 09:32
I'm guessing `svelte-jsoneditor` is being added to `optimizeDeps.exclude` in `vite.config.js`? Otherwise we'd need a repro to look into this.

**Comment by josdejong** [comment] 2022-11-08 09:43
I've had quite some issues related to non-ESM dependencies in the past, in the early days of SvelteKit+Vite, see for example this workaround: https://github.com/josdejong/svelte-jsoneditor/issues/121#issuecomment-1215598726. I haven't seen much issues lately though.

Does a workaround with `optimizeDeps.exclude` work in this case?

**Comment by ZaxyxaZ** [comment] 2022-11-08 21:16
@josdejong I think you were on the right track. The exclude parameter had no effect. And the messages out of Vite led me to think including up front might have an effect. I started adding the modules that Vite was reoptimizing one by one and this combination has addressed the dependency issue. Obviously, there is still a Vite issue to be dealt with but now there is at least a decent temporary work around.  Added to vite.config.js:

	optimizeDeps: {
		include: ['ajv-dist', 'immutable-json-patch', 'lodash-es','@fortawesome/free-regular-svg-icons', 'jmespath']

**Comment by josdejong** [comment] 2022-11-09 08:28
ahh, wow, that helps a lot! Thanks for sharing this workaround.

This makes sense (though it is a pity that this workaround is needed). I'm a bit surprised that for example `lodash-es` is needed, since that is a modern ESM only package.

**Comment by seandlg** [comment] 2022-11-09 10:39
> @josdejong I think you were on the right track. The exclude parameter had no effect. And the messages out of Vite led me to think including up front might have an effect. I started adding the modules that Vite was reoptimizing one by one and this combination has addressed the dependency issue. Obviously, there is still a Vite issue to be dealt with but now there is at least a decent temporary work around. Added to vite.config.js:
> 
> ```js
>   optimizeDeps: {
>     include: [
>       'ajv-dist', 
>       'immutable-json-patch',
>       'lodash-es',
>       '@fortawesome/free-regular-svg-icons',
>       'jmespath'
>     ]
>   }
> ```

This does not work for me, but you are right in the observation that the bug seems to be `devserver` related. I guess I'll wait for a few days/weeks and see if the problem evaporates with further updates to `vite`, since I fail to create a reproducible example 🤷

> > In the course of debugging the issue, I did notice a wrong type import from `svelte-jsoneditor`
> 
> Is this an issue in the library? If so, what is the bug? That sounds like easily solvable

This was a mistake on my end. `svelte-jsoneditor` is awesome! :-)

**Comment by ZaxyxaZ** [comment] 2022-11-09 16:37
> ahh, wow, that helps a lot! Thanks for sharing this workaround.
> 
> This makes sense (though it is a pity that this workaround is needed). I'm a bit surprised that for example `lodash-es` is needed, since that is a modern ESM only package.

Don't disagree - but was only following the bread crumbs left by the console output from Vite. I will say @seandlg that this fix is very specific to the set of packages we are using. As such the exact includes will be different if others run into this same issue.

**Comment by AlexRMU** [comment] 2022-11-10 07:54
It didn't help me either. Maybe you need to create a issue in vite?

**Comment by josdejong** [comment] 2022-12-06 11:45
I've described the workaround for this issue in the readme in a new section "Known issues". Besides that, I don't think this issue is actionable, I'll close this issue now. Feel free to reopen if needed.

**Closed by josdejong** 2022-12-06 11:45 UTC
